trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
-task: CopyFiles@2
input:
SourceFolder: '$(System.DefaultWorkingDirectory)'
Content 'index.html;script.js;style.css'
TargetFolder: '$(Build.ArtifactStagingDirectory)'
displayName: 'Copy the files'

-task: PublishBuildArtifacts@1
inputs:
  pathtoPublish: '$(Build.ArtifactStagingDirectory)'
  artifactName: 'drop'
  publishLocation: 'Container'
  displayName: 'publish the artifact'
